      SUBROUTINE HHBOOK1D(ID,NAME,NBIN,FMIN,FMAX)
      IMPLICITNONE
      INTEGER ID, NBIN
      REAL FMIN, FMAX
      CHARACTER*(*) NAME
*      write(*,*) ID, NAME, NBIN, FMIN, FMAX
      CALL HBOOK1(ID, NAME, NBIN, FMIN, FMAX, 0.)
      RETURN
      END

      SUBROUTINE HHBOOK2D(ID,NAME,XNBIN,XMIN,XMAX, YNBIN, YMIN, YMAX)
      IMPLICITNONE
      INTEGER ID, XNBIN, YNBIN 
      REAL XMIN, XMAX, YMIN, YMAX
      CHARACTER*(*) NAME
      CALL HBOOK2(ID, NAME, XNBIN, XMIN, XMAX, YNBIN, YMIN, YMAX, 0.)
      RETURN
      END


      SUBROUTINE HHF1(ID,X, WEIGHT)
      IMPLICITNONE
      INTEGER ID
      REAL X, WEIGHT
      CALL HF1(ID, X, WEIGHT)
      RETURN
      END

      SUBROUTINE HHF2(ID,X,Y, WEIGHT)
      IMPLICITNONE
      INTEGER ID
      REAL X, Y, WEIGHT
      CALL HF2(ID, X, Y, WEIGHT)
      RETURN
      END

      SUBROUTINE HHLIMIT(NWPAW)
      IMPLICITNONE
      INTEGER NWPAW
      CALL HLIMIT(NWPAW)
      RETURN
      END


      SUBROUTINE HHROPEN(LUN,CHTOP,CHFILE,CHOPT,LREC,ISTAT)
      IMPLICITNONE
      INTEGER LUN, LREC, ISTAT
      CHARACTER*(*) CHTOP
      CHARACTER*(*) CHFILE
      CHARACTER*(*) CHOPT
      CALL HROPEN(LUN,CHTOP,CHFILE,CHOPT,LREC,ISTAT);
      RETURN
      END

      SUBROUTINE HHREND(CHTOP)
      IMPLICITNONE
      CHARACTER*(*) CHTOP
      CALL HREND(CHTOP);
      RETURN
      END

      SUBROUTINE HHROUT(ID,ICYCLE,CHOPT)
      IMPLICITNONE
      INTEGER ID, ICYCLE
      CHARACTER*(*) CHOPT
      CALL HROUT(ID,ICYCLE,CHOPT)
      RETURN
      END

      
      SUBROUTINE HHREBIN(ID,X,Y,EX,EY,N, IFIRST, ILAST)
      IMPLICITNONE
      INTEGER ID, N, IFIRST, ILAST
      REAL X(*),Y(*),EX(*),EY(*)
      CALL HREBIN(ID,X,Y,EX,EY,N,IFIRST,ILAST)
      RETURN
      END


      SUBROUTINE HHRAMMAR(VEC, LEN)
      IMPLICITNONE
      INTEGER LEN
      REAL VEC(*)
      CALL RANMAR(VEC,LEN)
      RETURN
      END

      SUBROUTINE HHPAK(ID, CONTEN)
      IMPLICITNONE
      INTEGER ID
      REAL CONTEN(*)
      CALL HPAK(ID, CONTEN)
      RETURN
      END

      SUBROUTINE HHPAKE(ID, ERRORS)
      IMPLICITNONE
      INTEGER ID
      REAL ERRORS(*)
      CALL HPAKE(ID, ERRORS)
      RETURN
      END



      SUBROUTINE HHMAX(ID)
      IMPLICITNONE
      INTEGER ID
      CALL HMAX(ID)
      RETURN
      END


      SUBROUTINE HHSTATI(ID, ICASE, CHOICE, NUM)
      IMPLICITNONE
      INTEGER ID, ICASE, NUM
      CHARACTER*(*) CHOICE
      CALL HSTATI(ID, ICASE, CHOICE, NUM, 0.)
      RETURN
      END


      SUBROUTINE HHFITHN(ID,CHFUN,CHOPT,NP,PAR,STEP,PMIN,PMAX,SPAR,CH2)
      IMPLICITNONE
      INTEGER ID, NP 
      REAL PAR(*), STEP(*), PMIN(*), PMAX(*), SPAR(*), CH2
      CHARACTER*(*) CHFUN, CHOPT
      CALL HFITHN(ID,CHFUN,CHOPT,NP,PAR,STEP,PMIN,PMAX,SPAR,CH2)
      RETURN
      END




*      SUBROUTINE HHKIND(ID, KIND, CHOPT)
*      IMPLICITNONE
*      INTEGER ID 
*      INTEGER KIND(*)
*      CHARACTER*(*) CHOPT
*      CALL HKIND(ID, KIND, CHOPT)
*      RETURN
*      END

