#!/bin/bash
#
#   CMC100 FAST CAMAC controller driver
# Igor Alekseev & Dmitry Svirida, ITEP, Moscow
# to install a driver module from the current directory
#

TARGET_DIR=/lib/modules/`uname -r`/extra

if [ `id -u` == "0" ] ; then
#    make INSTALL_MOD_DIR=camac -C /lib/modules/`uname -r`/build M=`pwd` modules_install
    tgtdir=$TARGET_DIR
    mkdir -p $tgtdir
    cp cmcamac.ko $tgtdir
    /sbin/depmod -a
    if [ -x /sbin/udevcontrol ] ; then
        cp 50-cmcamac.rules /etc/udev/rules.d
        /sbin/udevcontrol reload_rules
    fi
else
    echo You must be root to run the installation
fi
