language: cpp
compiler:
  - gcc
before_script:
  - echo yes | sudo add-apt-repository ppa:marco89-7/root
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc6-dev-i386 root-system libmysql++-dev
  - mkdir build
  - cd build
  - cmake .. -DFORCE_32BIT=OFF
script: make
