SET(SQLITE_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/contrib/sqlite-amalgamation-3071700/)
SET(SQLITE_LIBRARY sqlite)

ADD_LIBRARY(
	${SQLITE_LIBRARY}
	SHARED
	${SQLITE_INCLUDE_DIR}/sqlite3.c
	)

IF(FORCE_32BIT)
	SET_TARGET_PROPERTIES(${SQLITE_LIBRARY} PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")
ENDIF()
