      SUBROUTINE HHBOOK1D(ID,NAME,NBIN,FMIN,FMAX)
      IMPLICITNONE
      INTEGER ID, NBIN
      REAL FMIN, FMAX
      CHARACTER*(*) NAME
*      write(*,*) ID, NAME, NBIN, FMIN, FMAX
      CALL HBOOK1(ID, NAME, NBIN, FMIN, FMAX, 0.)
      RETURN
      END


      SUBROUTINE HHBOOK2D(ID,NAME,XNBIN,XMIN,XMAX, YNBIN, YMIN, YMAX)
      IMPLICITNONE
      INTEGER ID, XNBIN, YNBIN 
      REAL XMIN, XMAX, YMIN, YMAX
      CHARACTER*(*) NAME
      CALL HBOOK2(ID, NAME, XNBIN, XMIN, XMAX, YNBIN, YMIN, YMAX, 0.)
      RETURN
      END

      SUBROUTINE HHBOOKN(ID,NAME)
      IMPLICITNONE
      INTEGER ID
      CHARACTER*(*) NAME
      CHARACTER*8 CHTAGS(7)
	DATA CHTAGS/'t_t','amp','chan','hbk_cont','iStrip','tdc','adc'/
      CALL HBOOKN(ID,'a row-wise ntuple',7,'//example',10000,CHTAGS)
      RETURN
      END

      SUBROUTINE HHFN(ID,EVENT)
      IMPLICITNONE
      INTEGER ID
      REAL EVENT(7) 
*      write(*,*) ID
*      write(*,*) EVENT(1), EVENT(2), EVENT(3), EVENT(4),EVENT(5) 
*      write(*,*) EVENT(6),EVENT(7) 
      CALL HFN(ID, EVENT)
      RETURN
      END


      SUBROUTINE HHF1(ID,X, WEIGHT)
      IMPLICITNONE
      INTEGER ID
      REAL X, WEIGHT
      CALL HF1(ID, X, WEIGHT)
      RETURN
      END

      SUBROUTINE HHF2(ID,X,Y, WEIGHT)
      IMPLICITNONE
      INTEGER ID
      REAL X, Y, WEIGHT
      CALL HF2(ID, X, Y, WEIGHT)
      RETURN
      END

      SUBROUTINE HHLIMIT(NWPAW)
      IMPLICITNONE
      INTEGER NWPAW
      CALL HLIMIT(NWPAW)
      RETURN
      END


      SUBROUTINE HHROPEN(LUN,CHTOP,CHFILE,CHOPT,LREC,ISTAT)
      IMPLICITNONE
      INTEGER LUN, LREC, ISTAT
      CHARACTER*(*) CHTOP
      CHARACTER*(*) CHFILE
      CHARACTER*(*) CHOPT
      CALL HROPEN(LUN,CHTOP,CHFILE,CHOPT,LREC,ISTAT);
      RETURN
      END

      SUBROUTINE HHREND(CHTOP)
      IMPLICITNONE
      CHARACTER*(*) CHTOP
      CALL HREND(CHTOP);
      RETURN
      END

      SUBROUTINE HHROUT(ID,ICYCLE,CHOPT)
      IMPLICITNONE
      INTEGER ID, ICYCLE
      CHARACTER*(*) CHOPT
      CALL HROUT(ID,ICYCLE,CHOPT)
      RETURN
      END

      
      SUBROUTINE HHREBIN(ID,X,Y,EX,EY,N, IFIRST, ILAST)
      IMPLICITNONE
      INTEGER ID, N, IFIRST, ILAST
      REAL X(*),Y(*),EX(*),EY(*)
      CALL HREBIN(ID,X,Y,EX,EY,N,IFIRST,ILAST)
      RETURN
      END


      SUBROUTINE HHRAMMAR(VEC, LEN)
      IMPLICITNONE
      INTEGER LEN
      REAL VEC(*)
      CALL RANMAR(VEC,LEN)
      RETURN
      END

      SUBROUTINE HHPAK(ID, CONTEN)
      IMPLICITNONE
      INTEGER ID
      REAL CONTEN(*)
      CALL HPAK(ID, CONTEN)
      RETURN
      END

      SUBROUTINE HHPAKE(ID, ERRORS)
      IMPLICITNONE
      INTEGER ID
      REAL ERRORS(*)
      CALL HPAKE(ID, ERRORS)
      RETURN
      END

