CFLAGS = -m32
LDFLAGS = -m32
PROGS = burcmc


burcmc : burcmc.o ../libcmc/libcmc.o

#clean:
#	-rm -f *.o
#	-rm -f burcmc
#
#cleanall: clean
#	cd $(CNIPOL_DIR)/bin; rm -f burcmc
#
#install:
#	cp burcmc $(CNIPOL_DIR)/bin
