include /vobs/libs/makefiles/MakeStd.inc

NAME = Tools

USESOLIBS = yes

PROG1 = cdevCmd
SRCS1 = cdevCmd.cpp
LIBS1 = cdevCns cdev includeCdev GenData rhicError Async setHist

PROG2 = sndpic
SRCS2 = sndpic.cpp
LIBS2 = $(LIBS1)

include $(MAKEDIR)/MakeApp.inc
